### ISSUE TITLE
Add current date and time by default while doing the entry

### ISSUE THREAD

**Issue by yashkite** [yashkite/UMoney#14]
while making manual entries we have to add the date and time and also show them in the recycler view via the most recent entry in the first place.

**Comment by yashkite** [comment]
Sumit, a friend of mine suggested a great resource for this issue.

reference link:- https://www.tutorialspoint.com/how-to-use-date-time-picker-in-android

now at this moment, we can able to save the date picker data inside the variable needed to save the data inside firebase so it will be get saved while adding the transaction manually.

**Comment by satnium** [comment]
check this out for epoch time (timestamp) ---- 
link --- https://www.epochconverter.com/

**Comment by yashkite** [comment]
things to get clear to solve this issues

- [ ] At which place Date picker and time picker storing there values
- [ ] Is Date picker and Time Picker giving default values without editing them
- [ ] How the firestore timestamp syntax looks like while writing the changes
- [ ] Convert the veriable values into timestamp syntax.
- [ ] Check the hashmap, String vs Object (Transaction Page)

after this new issue will be create about read operation.

**Comment by yashkite** [comment]
![image](https://user-images.githubusercontent.com/32860312/180645949-b51b55b7-8869-40fb-9978-bd05d20c4fee.png)

**Comment by yashkite** [comment]
I think we can go ahead with read operation what do you think @satnium

**Comment by yashkite** [comment]
New changes looks like this 

![Screenshot_2022-07-25-11-54-24-45_fad799079d3f45dfd96d7dc934ab9d8b.jpg](https://user-images.githubusercontent.com/32860312/180712472-61154b49-af2a-4ce0-8ea1-900c4f008e68.jpg)

**Comment by yashkite** [comment]
read and write is looking good i think its time to close this issue
