### ISSUE TITLE
Custom tag acivity 

### ISSUE THREAD

**Issue by satnium** [yashkite/UMoney#17]
by using this activity , an user can create its own tags by using custom names , icon and tags  by clicking on entering the recycler view   .
we are going to store values inside arraylist<> instead  of arrays .

**Comment by ghost** [comment]
checklist for this issue.

- [x]  make navigation tag menu to open tag add/edit/ delete page
- [x]  change tags from array to arraylist, and see that its working with the app and updating with database.
- [x]  Make a activity to create and delete the tags.
- [x]  assign all button onclick method and test if its working (read and write operation for tag).

**Comment by yashkite** [comment]
Implemented in dev branch
