### ISSUE TITLE
Navigation drawer with tags menu items

### ISSUE THREAD

**Issue by satnium** [yashkite/UMoney#18]
- [x]  create a navigation drawer 
- [x]  which will have an option of custom tags 
- [x] make menu items clickable

**Comment by yashkite** [comment]
@satnium hey connect the phone with the laptop via wire or wireless and check in the logcat that which error showing while crashing 
![image](https://user-images.githubusercontent.com/32860312/181349227-52aab3eb-f6e2-4a4c-8e3b-3f04605f6aa2.png)

**Comment by yashkite** [comment]
@satnium Any update related to the crash

**Comment by yashkite** [comment]
Implemented in dev branch
